version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: logbook-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: logbook
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - logbook-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: logbook-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - logbook-network

networks:
  logbook-network:
    driver: bridge

volumes:
  postgres_data: 